easy_admin:
  site_name: 'MovieDB'
  design:
    brand_color: '#1E90FF'
    menu: 
        - Movie
        - Category
  entities:
        # List the entity class name you want to manage
        Movie:
            class: App\Entity\Movie
            list: 
                fields:
                    - id
                    - title 
                    - { property: 'title', label: 'Titre'}
                    - releaseDate
                    - { property: 'releaseDate', label: 'Date de sortie'}
                    - director
                    - { property: 'director', label: 'Réalisateur'}
            form:
                fields:
                    - { type: 'group', columns: 6 }
                    - title
                    - imageFilename
                    - releaseDate
                    - { type: 'group', columns: 6 }
                    - director
                    - writers
                    - categories
                    - { type: 'group', columns: 12}
                    - { 
                        property: 'movieActors', 
                        type: 'collection', 
                        type_options: { 
                            entry_type: App\Form\MovieActorType,
                            entry_options: { label: false },
                            allow_add: true,
                            by_reference: false 
                        } 
                      }
        Category:
            class: App\Entity\Category
        Person:
            class: App\Entity\Person
        Post:
            class: App\Entity\Post

    
